-- local map = vim.api.nvim_set_keymap
-- local opts = { noremap = true, silent = true }
-- local ok, barbar = pcall(require, 'bufferline')
-- if not ok then
-- 	return
-- end
--
-- barbar.setup{
-- 	animation = true
-- }
-- -- Move to previous/next
-- map('n', '<A-,>', '<Cmd>BufferPrevious<CR>', opts)
-- map('n', '<A-.>', '<Cmd>BufferNext<CR>', opts)
-- -- Re-order to previous/next
-- map('n', '<A-<>', '<Cmd>BufferMovePrevious<CR>', opts)
-- map('n', '<A->>', '<Cmd>BufferMoveNext<CR>', opts)
-- -- Pin/unpin buffer
-- map('n', '<A-p>', '<Cmd>BufferPin<CR>', opts)
-- -- Close buffer
-- map('n', '<A-c>', '<Cmd>BufferClose<CR>', opts)
--
-- local nvim_tree_events = require('nvim-tree.events')
-- local bufferline_api = require('bufferline.api')
--
-- local function get_tree_size()
--   return require'nvim-tree.view'.View.width
-- end
--
-- nvim_tree_events.subscribe('TreeOpen', function()
--   bufferline_api.set_offset(get_tree_size())
-- end)
--
-- nvim_tree_events.subscribe('Resize', function()
--   bufferline_api.set_offset(get_tree_size())
-- end)
--
-- nvim_tree_events.subscribe('TreeClose', function()
--   bufferline_api.set_offset(0)
-- end)
